name: Docker Build and Publish

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}

jobs:
  buildAndPush:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs\/tags\/v}" >> $GITHUB_OUTPUT
          echo "CLEAN_VERSION=${${GITHUB_REF#refs\/tags\/v}/-*/}" >> $GITHUB_OUTPUT
          echo "SUFIX=${${GITHUB_REF#refs\/tags\/v}/*-/}" >> $GITHUB_OUTPUT

      - name: Get the image name
        id: get_name
        run: echo "IMAGE_NAME=${REPO_NAME/docker-}" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          [[ "${{ steps.get_version.outputs.VERSION }}" == *"-"* ]] && DOCKERFILE="Dockerfile.${{ steps.get_version.outputs.SUFIX }}" || DOCKERFILE="Dockerfile"
          docker build --build-arg VERSION=${{ steps.get_version.outputs.VERSION }} --build-arg CLEAN_VERSION=${{ steps.get_version.outputs.CLEAN_VERSION }} --build-arg BUILD_DATE="$(date +%Y/%m/%dT%H:%M:%S)" --file ${DOCKERFILE} --tag ${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} .
      
      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: docker push ${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Update latest Docker image
        run: docker tag ${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} ${{ steps.get_name.outputs.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: docker push ${{ steps.get_name.outputs.IMAGE_NAME }}:latest
